services:
  api:
    build: .
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./certs:/certs:ro
      - /home/brics/dataset:/dataset
    restart: unless-stopped
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
